name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Custom Test 1
      id: custom-test-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Custom Test 1
        setup-command: pip install pytest
        command: pytest test_2.py
        timeout: 10
        max-score: 50
    - name: Custom Fail
      id: custom-fail
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Custom Fail
        setup-command: Pytest test
        command: pytest test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CUSTOM-TEST-1_RESULTS: "${{steps.custom-test-1.outputs.result}}"
        CUSTOM-FAIL_RESULTS: "${{steps.custom-fail.outputs.result}}"
      with:
        runners: custom-test-1,custom-fail
